# Generated by Django 6.0 on 2025-12-22 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_profile_avatar_userstats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar',
        ),
    ]
