# Generated by Django 6.0 on 2025-12-24 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_lesson_bullets_lesson_duration_lesson_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonprogress',
            name='lesson_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='user_username',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
