# Generated by Django 6.0 on 2025-12-24 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_lessonprogress_lesson_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonprogress',
            name='lesson_title',
        ),
        migrations.RemoveField(
            model_name='lessonprogress',
            name='user_username',
        ),
    ]
